name: silverblue-ublue
description: Fedora Silverblue, with batteries and tweaks included.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 38
modules:
  - from-file: common/files.yaml
  - from-file: common/packages.yaml
  - from-file: common/bling.yaml
  - from-file: common/yafti.yaml
  - from-file: common/signing.yaml
