type: rpm-ostree
install:
  - steam-devices # Make steam controllers work
  - langpacks-en
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-gamemode
  - gamemode
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-light-style
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-blur-my-shell
  - qt5ct # Support qt themes
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  - gnome-system-monitor # We have a flapak for that
  - gnome-extensions-app # We have a flatpak for that
  # Remove built in extensions, except for background logo
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-classic-session # Fix dependency issues
  - gnome-terminal # Flatpak
  - gnome-terminal-nautilus # Fix dependency issues
  - gnome-tweaks # No unneeded apps
  - htop # Not used
  - nvtop # Not used
