type: rpm-ostree
install:
  - steam-devices # Make steam controllers work
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  - gnome-system-monitor # We have a flapak for that
  # Remove built in extensions, except for background logo
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-window-list
  - gnome-classic-session # Fix dependency issues
  - gnome-terminal # Flatpak
  - gnome-terminal-nautilus # Fix dependency issues
  - nautilus #flatpak
  - htop # Not used
  - nvtop # Not used
